version: "3.8"
services:
  eureka:
    hostname: eureka
    restart: unless-stopped
    build: .\eureka
    ports:
      - "8761:8761"
    networks:
      - local-mysql
      - ms-network
    container_name: eureka
    image: "eureka"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://eureka:8761/actuator/health"]
        interval: 10s
        timeout: 5s
        retries: 5
        start_period: 20s
    environment:
      - eureka.instance.hostname=eureka
      - eureka.client.service-url.defaultZone=http://eureka:8761/eureka/

  mysqldb-local:
    image: mysql:8
    networks:
      - local-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=locals
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10

  local:
    container_name: local
    build: .\Local
    ports:
      - "8091:8091"
    hostname: local
    environment:
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb-local/locals?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - eureka.client.service-url.defaultZone=http://eureka:8761/eureka
    image: "local"
    networks:
      - local-mysql
    depends_on:
      mysqldb-local:
        condition: service_healthy
      eureka:
          condition: service_healthy

volumes:
  cache:
    driver: local
networks:
  vaccination-mysql:
  local-mysql:
  ms-network:
    driver: bridge

