version: "3.8"
services:

  eureka:
    hostname: eureka
    restart: unless-stopped
    build: .\eureka
    ports:
      - "8761:8761"
    networks:
      - vaccination-mysql
      - ms-network
    container_name: eureka
    image: "eureka"
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://eureka:8761/actuator/health"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    environment:
      - eureka.instance.hostname=eureka
      - eureka.client.service-url.defaultZone=http://eureka:8761/eureka/

  mysqldb-association:
    image: mysql:8
    networks:
      - association-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=associationservice
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 5
            

  association:
    container_name: association
    build: .\Association
    ports:
      - "8087:8087"
    hostname: association
    environment:
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb-association/associationservice?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - eureka.client.service-url.defaultZone=http://eureka:8761/eureka
    image: "association"
    healthcheck:
      test: curl --fail http://association:8087 || exit 1
      interval: 60s
      retries: 5
      start_period: 15s
      timeout: 10s
    networks:
      - association-mysql
    restart: on-failure
    depends_on:
      mysqldb-association:
        condition: service_healthy
      eureka:
        condition: service_healthy


volumes:
  cache:
    driver: local
networks:
  vaccination-mysql:
  association-mysql:
  ms-network:
    driver: bridge

