version: "3.8"
services:

  angular:
    container_name: angular
    build: AngularApp
    ports:
      - "4200:80"
    networks:
      - ms-network
    image: "angular"
    

volumes:
  cache:
    driver: local
networks:
  vaccination-mysql:
  ms-network:
    driver: bridge