version: "3.8"
services:

  eureka:
    hostname: eureka
    restart: unless-stopped
    build: .\eureka
    ports:
      - "8761:8761"
    networks:
      - vaccination-mysql
    container_name: eureka
    image: "eureka"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://eureka:8761/actuator/health"]
        interval: 10s
        timeout: 5s
        retries: 5
        start_period: 20s
    environment:
      - eureka.instance.hostname=eureka
      - eureka.client.service-url.defaultZone=http://eureka:8761/eureka/
   

  mysqldb:
    image: mysql:8
    networks:
      - vaccination-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=vaccination
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10

  vaccination:
    container_name: vaccination
    build: .\Vaccination
    ports:
      - "8091:8091"
    hostname: vaccination
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb/vaccination?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - eureka.client.service-url.defaultZone=http://eureka:8761/eureka
    image: "vaccination"
    networks:
      - vaccination-mysql
    depends_on:
      mysqldb:
        condition: service_healthy
      eureka:
          condition: service_healthy  

networks:
  vaccination-mysql:
  

  