version: "3.8"
services:
  eureka:
    hostname: eureka
    restart: always
    build: .\eureka
    ports:
      - "8761:8761"
    networks:
      - ms-network
    container_name: eureka
    image: "eureka"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://eureka:8761/actuator/health"]
        interval: 10s
        timeout: 5s
        retries: 5
        start_period: 20s
    environment:
        eureka.instance.hostname: eureka
        eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka/
    
    
  redis:
    image: redis:6.2-alpine
    command: ["redis-server","--bind","redis","--port","6379"]
    restart: always
    hostname: redis
    container_name: redis
    networks:
      - ms-network
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT_NUMBER=6379
    ports:
      - "6379:6379"
    healthcheck:
        test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
        interval: 30s
        timeout: 10s
        retries: 5
    volumes: 
      - cache:/data
      
  sterilization:
    hostname: sterilization
    container_name: sterilization
    build: .\sterilization-veterinarian
    ports:
      - "8082:8082"
    networks:
      - ms-network
    hostname: sterilization
    environment:
      SPRING_APPLICATION_JSON: '{
        "eureka.client.server-url.default-zone"  : "http://eureka:8761/eureka",
        "spring.redis.host" : "redis",
        "spring.cache.type" : "redis",
        "spring.redis.port" : "6379"
      }'
    image: "sterilization"
    depends_on:
        eureka:
            condition: service_healthy 




volumes:
  cache:
    driver: local
networks:
  ms-network:
    driver: bridge