eureka:
  client:
    fetch-registry: "true"
    register-with-eureka: "true"
    serviceUrl:
      defaultZone: http://eureka:8761/eureka
spring:
  application:
    name: API-Gateway3
  cloud:
    gateway:
      routes:
        - id: vaccinationMs
          uri: http://vaccination:8091/
          predicates:
            - Path=/**
        - id: sterilizationMs
          uri: http://sterilization:8082/
          predicates:
            - Path=/api/**
server:
  port: "8888"
