eureka:
  client:
    fetch-registry: "true"
    register-with-eureka: "true"
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: API-Gateway3
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
      routes:
        - id: vaccinationMs
          uri: http://localhost:8091/
          predicates:
            - Path=/**
        - id: petMS
          uri: http://localhost:5000/
          predicates:
            - Path=/**
        - id: localMS
          uri: http://localhost:8094/
          predicates:
            - Path=/locals/**
        - id: rewardMS
          uri: http://localhost:8085/
          predicates:
            - Path=/rewards/**
  security:
    user:
      name: root
      password: root

server:
  port: "8888"
