eureka:
  client:
    fetch-registry: "true"
    register-with-eureka: "true"
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: API-Gateway3
  cloud:
    gateway:
      routes:
        - id: vaccinationMs
          uri: http://localhost:8091/
          predicates:
            - Path=/**

server:
  port: "8888"
