eureka:
  client:
    fetch-registry: "true"
    register-with-eureka: "true"
    serviceUrl:
      defaultZone: http://eureka:8761/eureka
spring:
  application:
    name: API-Gateway3
  cloud:
    gateway:
      routes:
      - id: petMS
        uri: http://pet:5000/
        predicates:
          - Path=/**
      - id: vaccinationMs
        uri: http://vaccination:8091/
        predicates:
          - Path=/**

server:
  port: "8888"
