eureka:
  client:
    fetch-registry: "true"
    register-with-eureka: "true"
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: API-Gateway3
  cloud:
    gateway:
      routes:
        - id: vaccinationMs
          uri: http://localhost:8091/
          predicates:
            - Path=/**
        - id: petMS
          uri: http://localhost:5000/
          predicates:
            - Path=/**
  security:
    user:
      name: root
      password: root

server:
  port: "8888"
