eureka:
  client:
    fetch-registry: "true"
    register-with-eureka: "true"
    serviceUrl:
      defaultZone: http://eureka:8761/eureka
spring:
  application:
    name: API-Gateway3
  cloud:
    gateway:
      routes:
        - id: sterilization-service
          uri: lb://sterilization-service
          order: 1
          predicates:
            - Path=/sterilizations/**,/veterinarians/**
        - id: vaccination-service
          uri: lb://vaccination-service
          order: 0
          predicates:
            - Path=/vaccines/**,/vaccineTypes/**
        - id: pet
          uri: lb://pets
          order: 2
          predicates:
            - Path=/pets/**
        - id: local-service
          uri: lb://local-service
          order: 3
          predicates:
            - Path=/locals/**
server:
  port: "8888"
